"""
https://leetcode.com/problems/find-the-difference/

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.


Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

"""
class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        dict_t = {}
        for c in t:
            if dict_t.get(c,0) > 0:
                dict_t[c] = dict_t[c] + 1
            else:
                dict_t.setdefault(c,1)

        for c in s:
            if dict_t.get(c,0) > 0:
                dict_t[c] = dict_t[c] - 1

        result = ''
        for key in dict_t.keys():
            if dict_t[key] > 0:
                result = key

        return result


#測試程式
if __name__ == '__main__':
    s = Solution()
    print(s.findTheDifference('123','1234'))
